version: 0.0.1.{build}

assembly_info:
  patch: true
  file: **\AssemblyInfo.*
  assembly_version: {version}
  assembly_file_version: {version}
  assembly_informational_version: {version}

pull_requests:  
  do_not_increment_build_number: true

branches:  
  only:
  - master

nuget:  
  disable_publish_on_pr: true

test: off

build_script:
- ps: .\Build.ps1

artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet

